### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by d-kleine** [rasbt/LLM-finetuning-scripts#4]
Hi Sebastian,

Could you please add a guideline how to use this repo to the readme (e.g. with Python version you have used) and add a _requirements.txt_ file for reproducibility please?

Thank you in advance!

**Comment by rasbt** [comment]
Good call. These were mainly the supplementary materials for some articles ... but you are right, I should have added requirements.txt files with version numbers. Unfortunately, I don't have them handy anymore but I'll leave this issue open. The next time I run the code I'll export the Python and library versions from the environment and add them to a requirements.txt.
